yoyogo:
  application:
    name: yoyogo_grpc_clientdemo    # go build grpc-demo/client --profile=test
    metadata: "grpc client demo"
    server:
      type: "console"
  cloud:
    discovery:
      cache:
        ttl: 30     # seconds
      type: "nacos"
      metadata:
        url: "120.53.133.30"
        port: 80
        namespace: "public"
        group: ""
        cluster: ""
        auth:
          enable: true
          username: "root"
          password: "1234"