yoyogo:
  application:
    name: yoyogo_demo_test
    metadata: "test"
    server:
      type: "fasthttp"
      address: ":8080"
      path: "app"
      max_request_size: 2096157
      session:
        name: "YOYOGO_SESSIONID"
        timeout: 3600
      tls:
        cert: ""
        key: ""
      mvc:
        template: "v1/{controller}/{action}"
        views:
          path: "./Static/templates"
          includes: [ "","" ]
      static:
        patten: "/"
        webroot: "./Static"
      jwt:
        header: "Authorization"
        secret: "12391JdeOW^%$#@"
        prefix: "Bearer"
        expires: 3
        enable: false
        skip_path: [
            "/info",
            "/v1/user/GetInfo",
            "/v1/user/GetSD"
        ]
      cors:
        allow_origins: ["*"]
        allow_methods: ["POST","GET","PUT", "PATCH"]
        allow_credentials: true
  cloud:
    apm:
      skyworking:
        address: localhost:11800
    discovery:
      type: "nacos"
      metadata:
        url: "120.53.133.30"
        port: 80
        namespace: "public"
        group_name: ""
    #    clusters: [""]
  #      type: "consul"
  #      metadata:
  #        address: "localhost:8500"
  #        health_check: "/actuator/health"
  #        tags: [""]
  #      type: "eureka"
  #      metadata:
  #        address: "http://localhost:5000/eureka"
  datasource:
    mysql:
      name: db1
      url: tcp(cdb-amqub3mo.bj.tencentcdb.com:10042)/yoyoBlog?charset=utf8&parseTime=True
      username: root
      password: 1234abcd
      debug: true
      pool:
        init_cap: 2
        max_cap: 5
        idle_timeout : 5
    redis:
      name: reids1
      url: 62.234.6.120:31379
      password:
      db: 0
      pool:
        init_cap: 2
        max_cap: 5
        idle_timeout: 5