yoyogo:
  application:
    name: yoyogo_demo_dev
    metadata: "develop"
    server:
      type: "fasthttp"
      address: ":8080"
      path: "app"
      max_request_size: 31457280
      session:
        name: "YOYOGO_SESSIONID"
        timeout: 3600
      tls:
        cert: ""
        key: ""
      mvc:
        template: "v1/{controller}/{action}"
        views:
          path: "./static/templates"
          includes: [ "","" ]
      static:
        patten: "/"
        webroot: "./static"
      jwt:
        header: "Authorization"
        secret: "12391JdeOW^%$#@"
        prefix: "Bearer"
        expires: 3
        enable: false
        skip_path: [
            "/info",
            "/v1/user/GetInfo",
            "/v1/user/GetSD"
        ]
      cors:
        allow_origins: ["*"]
        allow_methods: ["POST","GET","PUT", "PATCH"]
        allow_credentials: true
  cloud:
    apm:
      skyworking:
        address: localhost:11800
    discovery:
      cache:
        ttl: 30     # seconds
      strategy: "round-robin"    # round-robin  , weight-time ,  random
      type: "nacos"
      metadata:
        url: "nacos.yoyogo.run"
        port: 80
        namespace: "public"
        group: "DEFAULT_GROUP"
        cluster: ""
        configserver:
          dataId: "simple_demo"
        auth:
          enable: true
          username: "nacos"
          password: "nacos"
          endpoint: ""
          regionId: ""
          accessKey: ""
          secretKey: ""
          openKMS: false
#      type: "consul"
#      metadata:
#        address: "localhost:8500"
#        health_check: "/app/actuator/health"
#        token: ""
#        tags: [""]
#      type: "eureka"
#      metadata:
#         datacenter: ""
#         address:
#           - "http://sd.yoyogo.run/eureka"
#         ttl: 30   # seconds
#      type: "etcd"
#      metadata:
#        address:
#          - "81.70.154.55:32379"
#        namespace: "public"
#        ttl: 60
#        auth:
#          enable: true
#          username: "root"
#          password: "5z1fLbYw8A"
    configcenter:
      apollo:
        appid: "SampleApp"
        endpoint: "http://49.232.153.51:8080"    # admin:  http://49.232.153.51:8070/
        namespace: "application.yaml"
  datasource:
      pool:
        init_cap: 2
        max_cap: 5
        idle_timeout: 5
      db:
        name: db1
        type: mysql
        url: tcp(cdb-amqub3mo.bj.tencentcdb.com:10042)/yoyoBlog?charset=utf8&parseTime=True
        username: root
        password: 1234abcd
        debug: false
      redis:
        name: reids1
        url: m.yoyogo.run:6379
        password: 123.com
        db: 0
