application:
  name: demo_prod
  metadata: "prod hostenv"
  server:
    type: "fasthttp"
    address: ":8080"
    max_request_size: 2096157
    static:
      patten: "/"
      webroot: "./Static"
    views:
      path: "./Static/templates"
      includes: [ "","" ]
    jwt:
      header: "Authorization"
      secret: "12391JdeOW^%$#@"
      prefix: "Bearer"
      expires: 3
      enable: true
    cors:
      enable: true
      allow_origins: [ "*" ]
      allow_methods: [ "POST","GET","PUT", "PATCH" ]
      allow_credentials: true
server_discovery:
  type: "nacos"
  metadata:
    url: "localhost"
    port: 8848
    namespace: "public"
    #group_name: ""
    #clusters: [""]